name = "aichat-vegvisr"
compatibility_date = "2025-01-15"
pages_build_output_dir = "dist"

[[services]]
binding = "AUTH_WORKER"
service = "auth-worker"

[[services]]
binding = "DOMAIN_WORKER"
service = "test-domain-worker"

[[kv_namespaces]]
binding = "THEME_STUDIO_KV"
id = "1e3f20b8ed40453dbfa1f771012c99f2"
