name = "aichat-vegvisr"
account_id = "5d9b2060ef095c777711a8649c24914e"
compatibility_date = "2025-01-15"
pages_build_output_dir = "dist"

[[services]]
binding = "AUTH_WORKER"
service = "auth-worker"

[[services]]
binding = "DOMAIN_WORKER"
service = "test-domain-worker"

[[kv_namespaces]]
binding = "THEME_STUDIO_KV"
id = "c1489b0abee34a9d82f326b1b8f89c15"
